---
title: "Assignment E"
subtitle: "PSY 4960"
author: "Peter M Grund, Helen Yu, Petra Liu"
date: "4/6/2022"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

# Setup
```{r Setup}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Import data and dependencies}
library(tidyverse)
library(car)
```

This open-source data file can be found at <https://osf.io/te54b/>

```{r Upload data}
df <- read_csv("In-data/emerging_adult_data.csv")

```

# Clean data

```{r Add rows}
df$ID <- 1:nrow(df)
```

```{r Select variables}
df_analysis <- df %>%
  select(ID, mindful_1:mindful_biascheck, sex:race, school_coded, IDEA_1:`IDEA-bias-dummy`,
         income, stress_1:stress_bias_dummy, `moa1#1_1`:`MOA-ACH_dummy`) %>%
  select(-(sibling)) 

```

# Score measures
## IDEA
```{r Score IDEA}
df_analysis$exploration <- df_analysis %>% 
  select(IDEA_1, IDEA_2, IDEA_5, IDEA_6) %>%
  rowMeans()

```

## Measures of Adulthood
```{r Score measures of adulthood}
df_analysis$achievement <- df_analysis %>% 
  select(ID, starts_with("MOA")) %>% rowSums()

```

## Percieved Stress Scale
```{r Score Percieved Stress Scale}
df_analysis$stress_4 <- recode(df_analysis$stress_4, '5=1; 4=2; 3=3; 2=4; 1=5')
df_analysis$stress_5 <- recode(df_analysis$stress_5, '5=1; 4=2; 3=3; 2=4; 1=5')
df_analysis$stress_7 <- recode(df_analysis$stress_7, '5=1; 4=2; 3=3; 2=4; 1=5')
df_analysis$stress_8 <- recode(df_analysis$stress_8, '5=1; 4=2; 3=3; 2=4; 1=5')

df_analysis$stress_score <- df_analysis %>% select(stress_1:stress_10) %>% rowSums()
```

## Mindfulness
```{r Score mindfulness}
df_analysis$mindful_score <- df_analysis %>%
  select(starts_with("mindful")) %>%
  rowMeans()

```

# Preliminary data analysis
```{r Summarize data}
index_summary <- df_analysis %>%
  summarize(
    mean_mindful = mean(mindful_score, na.rm = TRUE),
    sd_mindful = sd(mindful_score, na.rm = TRUE),
    mean_achievement = mean(achievement, na.rm=TRUE),
    sd_achievement = sd(achievement, na.rm=TRUE),
    mean_stress = mean(stress_score, na.rm=TRUE),
    sd_stress = sd(stress_score, na.rm=TRUE)
    ) %>%
  write_csv("Out-data/index_measure_summary.csv")
```

```{r prelim regression analyses}
lm1 <- lm(achievement~stress_score, data=df_analysis)
summary(lm1)

cor.test(df_analysis$achievement, df_analysis$stress_score)

lm2 <- lm(achievement~exploration, data=df_analysis)
summary(lm2)
cor.test(df_analysis$achievement, df_analysis$exploration)
```
